apiVersion: apps/v1
kind: Deployment
metadata:
  # Используем имя релиза, чтобы избежать конфликтов
  name: {{ .Release.Name }}-myapp
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-myapp
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-myapp
    spec:
      containers:
        - name: myapp
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_CONN_STRING
              value: "{{ .Release.Name }}-redis:6379"
