stages:
  - build
  - test
  - deploy

build-job:
  tags:
    - docker
  stage: build
  script:
    - echo "Start build"

test-job:
  tags:
    - docker
  stage: test
  script:
    - echo "Start TEST stage"

deploy-job:
  tags:
    - docker
  stage: deploy
  only:
    - merge_request
  script:
    - echo "Start deploy"
