include:
  - project: 'itis-devops/sharafutdinovaa'
    ref: 'templates'
    file: '.before-script-template.yml'
  - project: 'itis-devops/sharafutdinovaa'
    ref: 'templates'
    file: '.after-script-template.yml'


stages:
  - build

build-job:
  tags:
    - docker
  stage: build
  image: alpine:latest
  script:
     - echo "My name is $GITLAB_USER_NAME" > file.txt
  artifacts:
    paths:
      - file.txt
    expire_in: 10m
